-- All keybinds have been moved to their respective plugin configuration files:
-- - Telescope: lua/plugins/telescope.lua
-- - LSP: lua/plugins/lsp.lua
-- - Diagnostics: lua/plugins/trouble.lua
-- - Tabs & Terminal: lua/plugins/ui.lua
-- - Amp: lua/plugins/agent.lua
-- - Git: lua/plugins/git.lua
-- - File Explorer: lua/plugins/files.lua
-- - Formatting: lua/plugins/format.lua
-- - Markdown: lua/plugins/markdown.lua
-- - Claude Code: lua/plugins/claude.lua
-- - Treesitter: lua/plugins/treesitter.lua
-- - Completion: lua/plugins/completion.lua
-- - Multi-cursor: lua/plugins/multicursor.lua
-- - Comments: lua/plugins/ui.lua
--
-- This file is kept for potential future global keybinds that don't belong to any specific plugin.
